[package]
name = "runtime-integration-tests"
version = "0.1.0"
authors = ["Centrifuge <admin@centrifuge.io>"]
edition = "2021"
license = "LGPL-3.0"
homepage = "https://centrifuge.io/"
repository = "https://github.com/centrifuge/centrifuge-chain"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0", default-features = false, features = ["derive"] }
fudge = { git = "https://github.com/centrifuge/fudge", branch = "polkadot-v0.9.43" }
lazy_static = "1.4.0"
serde = { version = "1.0.119" }
tokio = { version = "1.15", features = ["macros"] }
tracing-subscriber = "0.2"

# Substrate
## Substrate-Frame
frame-benchmarking = { git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.43" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
pallet-aura = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
pallet-collective = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
pallet-democracy = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
pallet-preimage = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
pallet-uniques = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }

## Substrate-Primitives
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
#sp-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }

## Substrate-Client
node-primitives = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
#sc-consensus-uncles = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-service = { git = "https://github.com/paritytech/substrate", features = ["rocksdb", "test-helpers"], branch = "polkadot-v0.9.43" }

# Polkadot
kusama-runtime = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.43" }
pallet-xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.43" }
polkadot-core-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.43" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.43" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.43" }
polkadot-runtime = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.43" }
polkadot-runtime-common = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.43" }
polkadot-runtime-parachains = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.43" }
rococo-runtime = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.43" }
xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.43" }

# Cumulus
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.43" }
parachain-info = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.43" }

# Orml pallets
orml-asset-registry = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, branch = "polkadot-v0.9.43" }
orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", branch = "polkadot-v0.9.43" }
orml-traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library", branch = "polkadot-v0.9.43" }
orml-xtokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", branch = "polkadot-v0.9.43" }

# Misc
xcm-emulator = { git = "https://github.com/branan/xcm-simulator", branch = "master" }

# Local
altair-runtime = { path = "../altair" }
centrifuge-runtime = { path = "../centrifuge" }
cfg-primitives = { path = "../../libs/primitives" }
cfg-traits = { path = "../../libs/traits" }
development-runtime = { path = "../development" }
runtime-common = { path = "../common" }

[dev-dependencies]
getrandom = { version = "0.2", features = ["js"] }
hex = { version = "0.4.3", default_features = false }

cfg-traits = { path = "../../libs/traits" }
cfg-types = { path = "../../libs/types" }
cfg-utils = { path = "../../libs/utils" }

ethereum = { version = "0.14.0", default-features = false }

pallet-evm = { git = "https://github.com/moonbeam-foundation/frontier", default-features = false, branch = "moonbeam-polkadot-v0.9.43" }
pallet-evm-chain-id = { git = "https://github.com/moonbeam-foundation/frontier", default-features = false, branch = "moonbeam-polkadot-v0.9.43" }

connectors-gateway-routers = { path = "../../pallets/connectors-gateway/routers" }
pallet-block-rewards = { path = "../../pallets/block-rewards" }
pallet-connectors = { path = "../../pallets/connectors" }
pallet-connectors-gateway = { path = "../../pallets/connectors-gateway" }
pallet-ethereum-transaction = { path = "../../pallets/ethereum-transaction" }
pallet-investments = { path = "../../pallets/investments" }
pallet-loans = { path = "../../pallets/loans" }
pallet-permissions = { path = "../../pallets/permissions" }
pallet-pool-registry = { path = "../../pallets/pool-registry" }
pallet-pool-system = { path = "../../pallets/pool-system" }
pallet-rewards = { path = "../../pallets/rewards" }

pallet-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
pallet-xcm-transactor = { git = "https://github.com/moonbeam-foundation/moonbeam", default-features = false, rev = "93548eeba1e32361c401c58c87596b400707557a" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = true, branch = "polkadot-v0.9.43" }
xcm-executor = { git = "https://github.com/paritytech/polkadot", default-features = true, branch = "release-v0.9.43" }

pallet-collator-selection = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.43" }

[features]
default = [
  "runtime-development",
  "development-runtime/instant-voting",
]
fast-runtime = ["development-runtime/fast-runtime"]
std = [
  "altair-runtime/std",
  "centrifuge-runtime/std",
  "cfg-primitives/std",
  "cumulus-primitives-core/std",
  "development-runtime/std",
  "frame-benchmarking/std",
  "frame-support/std",
  "frame-system/std",
  "kusama-runtime/std",
  "node-primitives/std",
  "orml-asset-registry/std",
  "orml-tokens/std",
  "orml-traits/std",
  "orml-xtokens/std",
  "pallet-aura/std",
  "pallet-balances/std",
  "pallet-investments/std",
  "pallet-transaction-payment/std",
  "pallet-uniques/std",
  "pallet-xcm/std",
  "parachain-info/std",
  "codec/std",
  "polkadot-core-primitives/std",
  "polkadot-parachain/std",
  "polkadot-primitives/std",
  "polkadot-runtime/std",
  "polkadot-runtime-common/std",
  "polkadot-runtime-parachains/std",
  "rococo-runtime/std",
  "runtime-common/std",
  "sc-executor/std",
  "serde/std",
  "sp-api/std",
  "sp-consensus-aura/std",
  "sp-consensus-babe/std",
  "sp-consensus-slots/std",
  "sp-core/std",
  "sp-inherents/std",
  "sp-runtime/std",
  "sp-tracing/std",
  "xcm/std",
  "getrandom/std",
]

runtime-benchmarks = [
  "default",
  "development-runtime/runtime-benchmarks",
  "frame-benchmarking/runtime-benchmarks",
  "kusama-runtime/runtime-benchmarks",
  "fudge/runtime-benchmarks",
  "altair-runtime/runtime-benchmarks",
  "centrifuge-runtime/runtime-benchmarks",
  "cfg-primitives/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "orml-asset-registry/runtime-benchmarks",
  "orml-tokens/runtime-benchmarks",
  "orml-xtokens/runtime-benchmarks",
  "pallet-balances/runtime-benchmarks",
  "pallet-investments/runtime-benchmarks",
  "pallet-uniques/runtime-benchmarks",
  "pallet-xcm/runtime-benchmarks",
  "polkadot-parachain/runtime-benchmarks",
  "polkadot-primitives/runtime-benchmarks",
  "polkadot-runtime/runtime-benchmarks",
  "polkadot-runtime-common/runtime-benchmarks",
  "polkadot-runtime-parachains/runtime-benchmarks",
  "rococo-runtime/runtime-benchmarks",
  "runtime-common/runtime-benchmarks",
  "sc-service/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
]
runtime-development = []
runtime-altair = []
runtime-centrifuge = []
